#ifndef LEXICO_H
#define LEXICO_H

#include <stdio.h>

typedef enum {
    // Tipos e Valores
    TOKEN_INTEIRO, TOKEN_REAL, TOKEN_CADEIA,
    TOKEN_IDENTIFICADOR, 
    TOKEN_VALOR_INTEIRO, TOKEN_VALOR_REAL,
    
    // Operadores Aritméticos e Pontuação
    TOKEN_ATRIBUICAO,       // =
    TOKEN_SOMA, TOKEN_SUBTRACAO, TOKEN_MULTIPLICACAO, TOKEN_DIVISAO,
    TOKEN_PONTO_VIRGULA, TOKEN_ABRE_PARENTESES, TOKEN_FECHA_PARENTESES,
    TOKEN_ABRE_CHAVE, TOKEN_FECHA_CHAVE,
    TOKEN_ABRE_COLCHETE, TOKEN_FECHA_COLCHETE,
    TOKEN_VIRGULA, TOKEN_PONTO,
    
    // Operadores Relacionais
    TOKEN_IGUAL_IGUAL, TOKEN_DIFERENTE, TOKEN_MENOR, TOKEN_MAIOR,
    TOKEN_MENOR_IGUAL, TOKEN_MAIOR_IGUAL, TOKEN_OPERADOR,

    // Operadores Lógicos
    TOKEN_E, TOKEN_OU,
    TOKEN_NAO,           
    
    // Palavras-chave de Controle
    TOKEN_SE, TOKEN_SENAO, TOKEN_ENQUANTO, TOKEN_PARA, TOKEN_DE, TOKEN_ATE,
    TOKEN_EXIBIR, TOKEN_LEIA, TOKEN_FUNCAO, TOKEN_RETORNO, TOKEN_REGISTRO,
    TOKEN_INICIO, TOKEN_FIM, TOKEN_ERRO
} TipoToken;

typedef struct {
    TipoToken tipo;
    char lexema[100];
    int linha;
} Token;

Token proximo_token(FILE* arquivo);

#endif